Railroad = ''
WeekEnding = ''
TrainSpeed_ByTrainType_IntermodalTrain = 
TrainSpeed_ByTrainType_Manifest = 
TrainSpeed_ByTrainType_CoalUnit = 
TrainSpeed_ByTrainType_GrainUnit = 
TrainSpeed_ByTrainType_AllTrains = 
TerminalDwell_FDLYard = 
TerminalDwell_HarrisonYard = 
TerminalDwell_JacksonYard = 
TerminalDwell_MacMillanYard = 
TerminalDwell_MarkhamYard = 
TerminalDwell_SymingtonYard = 
TerminalDwell_TascherauYard = 
TerminalDwell_ThorntonYard = 
TerminalDwell_WalkerYard = 
TerminalDwell_EntireRailroad = 