Railroad = ''
Title = ''
CarsOnLine_ByCarOwner_System = 
CarsOnLine_ByCarOwner_ForeignRR = 
CarsOnLine_ByCarOwner_Private = 
CarsOnLine_ByCarType_Box = 
CarsOnLine_ByCarType_CoveredHopper = 
CarsOnLine_ByCarType_Gondola = 
CarsOnLine_ByCarType_IntermodalCar = 
CarsOnLine_ByCarType_MultilevelCar = 
CarsOnLine_ByCarType_OpenHopper = 
CarsOnLine_ByCarType_Tank = 
CarsOnLine_ByCarType_Other = 
TrainSpeed_ByTrainType_IntermodalTrain = 
TrainSpeed_ByTrainType_Manifest = 
TrainSpeed_ByTrainType_CoalUnit = 
TrainSpeed_ByTrainType_GrainUnit = 
TrainSpeed_ByTrainType_AllTrains = 
TerminalDwell_HarrisonYard = 
TerminalDwell_FDLYard = 
TerminalDwell_JacksonYard = 
TerminalDwell_MacMillanYard = 
TerminalDwell_MarkhamYard = 
TerminalDwell_SymingtonYard = 
TerminalDwell_TascherauYard = 
TerminalDwell_ThorntonYard = 
TerminalDwell_WalkerYard = 
TerminalDwell_EntireRailroad = 
