Railroad = 'BNSF'
WeekEnding = '20170407'
TrainSpeed_ByTrainType_IntermodalTrain = 31.8
TrainSpeed_ByTrainType_Manifest = 20.1
TrainSpeed_ByTrainType_MultilevelTrain = 24.6
TrainSpeed_ByTrainType_CoalUnit = 21.2
TrainSpeed_ByTrainType_GrainUnit = 21.7
TrainSpeed_ByTrainType_AllTrains = 24
TerminalDwell_Barstow = 41.4
TerminalDwell_Denver = 32.8
TerminalDwell_FortWorth = 17.6
TerminalDwell_Galesburg = 39.7
TerminalDwell_Houston = 23.5
TerminalDwell_KansasCity = 35.2
TerminalDwell_Lincoln = 36
TerminalDwell_Memphis = 18.9
TerminalDwell_Northtown = 31.7
TerminalDwell_Pasco = 35.4
TerminalDwell_Tulsa = 39
TerminalDwell_EntireRailroad = 27.9