Railroad = 'UP'
WeekEnding = '20170407'
TrainSpeed_ByTrainType_IntermodalTrain = 29.6
TrainSpeed_ByTrainType_Manifest = 22.3
TrainSpeed_ByTrainType_MultilevelTrain = 24.8
TrainSpeed_ByTrainType_CoalUnit = 24.9
TrainSpeed_ByTrainType_GrainUnit = 22.7
TrainSpeed_ByTrainType_AllTrains = 24.7
TerminalDwell_Chicago = 33.1
TerminalDwell_FortWorth = 35.5
TerminalDwell_Hinkle = 34.7
TerminalDwell_HoustonEnglewood = 29.6
TerminalDwell_HoustonSettegast = 32.3
TerminalDwell_KansasCity = 38.5
TerminalDwell_Livonia = 32
TerminalDwell_NorthLittleRock = 30.1
TerminalDwell_NorthPlatteEast = 26.5
TerminalDwell_NorthPlatteWest = 29.8
TerminalDwell_PineBluff = 28.2
TerminalDwell_Roseville = 35.7
TerminalDwell_WestColton = 37.8
TerminalDwell_EntireRailroad = 28.7