Railroad = 'NS'
WeekEnding = '20170407'
TrainSpeed_ByTrainType_IntermodalTrain = 27.3
TrainSpeed_ByTrainType_Manifest = 18.9
TrainSpeed_ByTrainType_MultilevelTrain = 20.6
TrainSpeed_ByTrainType_CoalUnit = 16.3
TrainSpeed_ByTrainType_GrainUnit = 16.5
TrainSpeed_ByTrainType_AllTrains = 21
TerminalDwell_Allentown = 26.8
TerminalDwell_Atlanta = 12.8
TerminalDwell_Bellevue = 32.4
TerminalDwell_Birmingham = 40.2
TerminalDwell_Chattanooga = 49.7
TerminalDwell_Columbus = 30.3
TerminalDwell_Conway = 26.4
TerminalDwell_Decatur = 23.9
TerminalDwell_Elkhart = 38.9
TerminalDwell_Linwood = 31.3
TerminalDwell_Macon = 29.3
TerminalDwell_NewOrleans = 18.2
TerminalDwell_Roanoke = 45
TerminalDwell_Sheffield = 47
TerminalDwell_EntireRailroad = 26.8