Railroad = 'KCS'
WeekEnding = '20170407'
TrainSpeed_ByTrainType_IntermodalTrain = 30
TrainSpeed_ByTrainType_Manifest = 26.2
TrainSpeed_ByTrainType_MultilevelTrain = 30
TrainSpeed_ByTrainType_CoalUnit = 24
TrainSpeed_ByTrainType_GrainUnit = 24.4
TrainSpeed_ByTrainType_AllTrains = 26.8
TerminalDwell_Jackson = 30.2
TerminalDwell_KansasCity = 17.8
TerminalDwell_Laredo = 32.6
TerminalDwell_Monterrey = 25
TerminalDwell_NuevoLaredo = 18.2
TerminalDwell_Sanchez = 42.5
TerminalDwell_SanLuisPotosi = 13.6
TerminalDwell_Shreveport = 36.3
TerminalDwell_EntireRailroad = 23.2