Railroad = 'CN'
WeekEnding = '20170407'
TrainSpeed_ByTrainType_IntermodalTrain = 28.4
TrainSpeed_ByTrainType_Manifest = 24.5
TrainSpeed_ByTrainType_CoalUnit = 24.6
TrainSpeed_ByTrainType_GrainUnit = 22.3
TrainSpeed_ByTrainType_AllTrains = 25.6
TerminalDwell_FDLYard = 21.7
TerminalDwell_HarrisonYard = 22.5
TerminalDwell_JacksonYard = 13.3
TerminalDwell_MacMillanYard = 19
TerminalDwell_MarkhamYard = 13.3
TerminalDwell_SymingtonYard = 22.3
TerminalDwell_TascherauYard = 13
TerminalDwell_ThorntonYard = 9.5
TerminalDwell_WalkerYard = 18.8
TerminalDwell_EntireRailroad = 15.3